version: "3.7"

services:
  blog:
    image: jekyll/jekyll:latest
    command: jekyll serve --force_polling --drafts --livereload --trace
    ports:
      - "4000:4000"
    volumes:
      - ".:/srv/jekyll"
    environment:
      JEKYLL_UID: 1001
      JEKYLL_GID: 1001